version: "3.0"

services:
  couchdb:
    container_name: obsidian-couchdb
    image: couchdb
    restart: unless-stopped
    environment:
      COUCHDB_USER: ${username}
      COUCHDB_PASSWORD: ${password}
    volumes:
      - /mnt/docker/obsidian/couchdb-data:/opt/couchdb/data
      - /mnt/docker/obsidian/couchdb-etc:/opt/couchdb/etc/local.d
    networks:
      -  nginx_bridge

networks:
  nginx_bridge:
    name: nginx_bridge
    external: true
