version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - /mnt/nas:/data
    environment:
      MINIO_ROOT_USER: ${ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MINIO_SERVER_URL: ${SERVER_URL}
      MINIO_REGION: ${REGION}
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
