version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: php-7-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - php-7-mysql-data:/var/lib/mysql
    # expose:
    #   - "3306"
    healthcheck:
          test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
          interval: 5s
          retries: 55
          start_period: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-7-admin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: php-7-db
      PMA_PORT: 3306
    restart: always
    ports:
      - "${ADMIN_PORT}:80"

  php-apache:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php-7-server
    restart: always
    #image: php:7.4-apache
    depends_on:
      mysql:
        condition: service_healthy
    volumes: 
      - ./htdocs:/var/www/html
    ports:
      - "${SERVER_PORT}:80"

volumes:
  php-7-mysql-data: